name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write  # Required to commit the lock file

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Removed `cache: npm` to avoid lock file error

      - name: Install dependencies (generate lock file if missing)
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found. Using npm ci..."
            npm ci
          else
            echo "package-lock.json not found. Running npm install to generate it..."
            npm install
          fi

      - name: Commit lock file if it was generated
        run: |
          if [ ! -f package-lock.json ]; then
            echo "No lock file present after install. Skipping commit."
            exit 0
          fi

          if git diff --quiet package-lock.json; then
            echo "No changes to lock file. Nothing to commit."
            exit 0
          fi

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package-lock.json
          git commit -m "Generate package-lock.json [skip ci]" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
